### ISSUE TITLE
HTTP erro 403

### ISSUE THREAD

**Issue by SilasK** [Darkbladecr/pyresearch#1]
I got this error, do you have an Idea what to do?

![image](https://cloud.githubusercontent.com/assets/7523034/21346829/62103198-c6a6-11e6-9eb7-c04f001bea7e.png)

**Comment by Darkbladecr** [comment]
Hey there,
Error 403 means forbidden. Do you want to double check you have access to the Scopus database?

Try the "Citations Overview" here:
https://dev.elsevier.com/metadata.html#!/Citations_Overview/CitationsOverview
The settings are all correct by default, but it will print out errors if your IP address is not enabled for Scopus. In which case you should get in contact with them directly.

I can only access it through my institutions WIFI or VPN.

**Comment by SilasK** [comment]
Thank you Stefan,

I retried it with VPN to my institution and I have access to Scopus. It should be something else.

Kind regards

**Comment by Darkbladecr** [comment]
Ah I think it is because of the recent change of protocol for PUBMED to run all requests through https now: https://www.ncbi.nlm.nih.gov/home/develop/https-guidance.shtml

Let me see if this is the cause and update.

**Comment by Darkbladecr** [comment]
Your error is originating from the Enterez call on the Biopython package. If it's urgent try updating your biopython to the latest package (v1.6.8) with pip, otherwise I'll fix it in the next 48 hours.

`sudo pip install biopython --upgrade`

**Comment by Darkbladecr** [comment]
I have updated the `requirements.txt` you can either run
`sudo pip install biopython --upgrade`
or
`sudo pip install -r requirements.txt` 
again. Let me know if this solves the problem!

**Comment by SilasK** [comment]
Perfect. I updated the Bio-python and now it works. 

May be you can put a phrase on the read me that you have to be connected to your institution with Scopus access. I wondered for some time If you need a API-key like for web of science.
